### PR TITLE
joyent/python-manta#42 support ~~ and ~~/ forms

### PR DESCRIPTION
**Pull request by cburroughs**

### CODE REVIEW

**Comment by tgross** [comment]
Had to hack around this in https://github.com/autopilotpattern/mysql/pull/85/commits/d53c5f95dfe31ba0172e5f3082eb5d8506a92dd0 as well... maybe it should be done in the library rather than in the mantash command line client?

**Comment by trentm** [comment]
@cburroughs Did you want to revive this? Just would need a rebase and move of the changelog entry to the latest unreleased section.  I agree with tgross's thought that '~~' handling should really be in the lib -- but that could be added separately.

**Comment by cburroughs** [comment]
I intend to (eventually), yes.

**Review by trentm — CHANGES_REQUESTED** [review]
LGTM. This needs a rebase? to get the 2.7.0 changes in CHANGES.md, and move the added bullet to the "not yet released" section.

**Pull request closed without merging**
